### PR TITLE
Huge rewrite of mhchem 3.0.0

### PR DESCRIPTION
**Pull request by mhchem**
- Complete rewrite of syntax parser
- Staggered layout for charges (IUPAC style)
- Improved spacing and space handling: 1/2 X^{2-} v, $n-1$ H^3HO(g), ^{22,98}_{11}Na, ...
- Decimal amounts: 0.5 H2O, 0,5 H2O
- Advanced charge/bond/hyphen distinction: OH-(aq), \mu-Cl, -H- ...
- Decimal and negative superscripts/subscripts: ^0_-1n-, ^{22.98}_{11}Na
- Superscript electrons: OCO^{.-}
- IUPAC fraction style: (1/2)H2O
- Auto-italic variables: n H2O, nH2O, NO_x, but pH
- Improved scanning: Fe^n+, X_\alpha, NO_$x$, $\alpha$$a$, ...
- Some unicode input, e.g. arrows
- {text} text escape
- \bond{3}
- Arrow arguments now parsed as \ce: A ->[H2O] B, A ->[$x$] B
- <--> arrow
- More operators: A + B = C - D, \pm
- Recursion works (\ce inside \ce)
- Removed hardly used synonyms \cf, \cee and command \hyphen
- Excited state: X^*
- Ellipsis vs bond: A...A, B...B, ...
- Punctuation: , ;
- Dissociation constant: pKa
- Orbitals: sp^2, s^{0.5}p^3-N
- Kroeger-Vink notation
- Better-looking Fast-HTML rendering: \ce{A + _{a}X}
- Many other things
- Side-effects for non-standard input

### CODE REVIEW

**Comment by mhchem** [comment]
Manual and test drive can be found at https://mhchem.github.io/MathJax-mhchem/

**Comment by pkra** [comment]
Awesome, Martin!

**Comment by dpvc** [comment]
Indeed, very, very nice!

**Comment by pkra** [comment]
@dvpc, @mhchem  is this ready to merge or is additional review planned on https://github.com/mhchem/MathJax-mhchem/?

**Comment by dpvc** [comment]
I wasn't planning any additional review unless @mhchem would like it.  I know there were changes for `\pu`, so if either of you want me to look that over, I will.

**Comment by pkra** [comment]
Sorry, I closed this accidentally!

**Comment by pkra** [comment]
> I wasn't planning any additional review unless @mhchem would like it. I know there were changes for \pu, so if either of you want me to look that over, I will.

No need from my end.

**Comment by pkra** [comment]
Now live on the CDN http://cdn.mathjax.org/mathjax/contrib/mhchem/mhchem.js

**Comment by dpvc** [comment]
Nice!  Congratulations @mhchem!

**Comment by pkra** [comment]
> Nice! Congratulations @mhchem!

I'll second that and add another huge round of thanks!

:clap: :clap: :clap: :fireworks: :fireworks: :fireworks: :fireworks: :clap: :clap: :clap:

**Comment by mhchem** [comment]
You are so kind! Thanks!

**Pull request merged**
