### PR TITLE
Mimicking LaTeX Physics Package

### PR DESCRIPTION
**Pull request by KolenCheung**
In LaTeX, when you `\usepackage{physics}`, you used the [LaTeX Physics Package](http://www.ctan.org/pkg/physics).
This extension is to mimick that in MathJax.

### CODE REVIEW

**Comment by pkra** [comment]
Very cool! This is an awesome addition and looks good to me.

There's only a small, formal problem: you should add licensing information to both the packed and the unpacked extension. Otherwise, your code has no actual license :-( You might want to compare how the other extensions do it.

**Comment by KolenCheung** [comment]
Thanks! This is the first time I submitted anything open source so I missed that. I thought the license.txt is enough.

I also want to ask a question: in the Physics package in LaTeX, some commands are defined with optional arguments. 
e.g. \dv (differentials) have the following possibilities:

- optional boolean: \dv or \dv*, 
- and each of them can have an optional [] like \dv[]{} or \dv{}, 
- and then it can also have variable no. of arguments like \dv{} and \dv{}{}.

Are there a way to write MathJax Macro like this too? Thanks!

**Comment by pkra** [comment]
Sorry for the delay, I was travelling. Thanks for updating the PR.

Regarding the questions,

* for examples handling optional booleans see e.g., https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/AMSmath.js#L120-L127
* To get brackets etc, check out the `getBrackets`, `getDimen` etc in the [TeX input jax](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js)

**Comment by KolenCheung** [comment]
Thanks for the reply. I tried to follow the first link and write something like:
	Macros: {
		vb: ['\\mathbf'],
		'vb*': ['\\boldsymbol']
	}
But it seems it doesn't work. The difference is in the AMSmath the * appears in an environment, but I want to include it in a Macros. What did I miss?
Thanks again.

**Comment by pkra** [comment]
Hm. I'm not sure what's happening. @dpvc could you help out?

**Comment by dpvc** [comment]
Macro names in TeX are either a single character (like `\{`) or a string or alphabetic characters (like `\sum`).  You can't mix non-alphabetic with alphabetic characters, and that even includes numbers (technically, it can be done, but requires changing the category codes of the non-alphabetic characters, which MathJax doesn't support).  So you can't define `\vb*` separately from `\vb` even in true TeX.  

What `\vb` does in TeX is look at the next character after the macro to see if it is an asterisk and does one thing if it is and a different thing if it isn't.  You can do that in MathJax, but must do so through javascript code.  This is how most of the macros are defined in MathJax, and Peter was trying to point you to the code where this is done.  He actually pointed to where environments are defined instead, which is a bit misleading, since the starred and unstarred versions are handled separately.  A better example might be to look at [operatorname](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/AMSmath.js#L101), which is defined by the javascript function [HandleOperatorName](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/AMSmath.js#L221-L227).  This uses the `GetStar()` function to determine if there is a star following the control sequence or not.  This also might be a good one to look at because it does a string substitution (like a macro) rather than building the internal MathML structure directly.

I notice that a number of the macros in the physics package allow arguments in parentheses as well as braces.  For that, you would need to do something like the `GetStar()` function, but look for parentheses instead, and then search ahead for the closing parenthesis to get the argument.  This can be done using the [GetUpTo()](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js#L1987-L2007) function.  There are several other service routines in the same area (like `GetArgument()`, `GetBrackets()`, `ParseArg()` and `ParseUpTo()`) that you will find useful if you want to implement more of the physics package functionality.

At some point, you will probably need to produce the internal MathML rather than just do string substitutions.  You should look at the functions in the TeX input jax, like [Frac](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js#L1987-L2007), and the others nearby for examples of how that is done.  See also the [Extension Authoring](https://github.com/mathjax/MathJax-docs/wiki/Tutorial-Extension-Authoring#more-advanced-extensions) wiki page for some more details.

It would be great to have some more good examples of this, so if you want to extend the functionality of your physics extension, that would be great.  You can ask questions here, or on the [MathJax Development Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-dev).

**Comment by pkra** [comment]
@KolenCheung did you want to work on this some more or should I merge it?

**Pull request merged**
