### PR TITLE
Added macros with alternative names

### PR DESCRIPTION
**Pull request by ickc**
c.f. [Mimicking LaTeX Physics Package by ickc · Pull Request #16 · mathjax/MathJax-third-party-extensions](https://github.com/mathjax/MathJax-third-party-extensions/pull/16).

The problems mentioned there are still unsolved, due to my inability in Javascript and MathJax.

I only added alternative def to the macros (e.g. `\absolutevalue` in addition to `\abs`), and changed the file organizations.

If anyone has the time and ability to do one example (e.g. `\dv` that has a mix of all the difficulties mentioned), I am willing to apply the same tricks to the other cases (if I can...).

### CODE REVIEW

**Comment by pkra** [comment]
This is great! I'm wondering if it might be better to keep a separate repository for the development files and only submit a ready-to-use copies here. You could still use our issue tracker to discuss and call for contributors.

**Comment by pkra** [comment]
Regarding `\dv`, I would look at similarly complx macros in the [TeX input](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js) and the [AMSmath extension](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/AMSmath.js). For example, look at those using `getBrackets` if you're trying to handle brackets; genfrac in AMSmath might be useful. From a quick look, for `\grande` it seems enough to add a wrapping mrow element (since that's how MathML decided stretchiness). For starred versions, I'm not sure MathJax differentiates non-environments (but check AMSmath for those);  for `\dv*` maybe beveled mfrac's are enough, check out http://docs.mathjax.org/en/latest/advanced/extension-writing.html#more-advanced-extensions

**Comment by pkra** [comment]
Correction for `\grande`; you'll probably need to do more. But maybe just use `\Big` etc or look at its definition in the TeX input.

**Comment by ickc** [comment]
Hi, I added some improvements including automatic bracing sizes, spacing of the operators, etc. I still didn't have time to figure out how to go beyond string substitution though. May be I will have more time on Summer to revisit them. For now, I think it's the best I can do.

**Comment by pkra** [comment]
Thanks for the update and all your work -- we greatly appreciate it! We would prefer it if this repo would not need to track the development files, i.e., only add the extension, readme (with reference to your repo), and license information. Would that be ok for you?

**Comment by ickc** [comment]
I see. I will create another branch and make a new pull request. Thanks.

**Comment by pkra** [comment]
Thanks so much!

**Pull request closed without merging**
