### PR TITLE
mhchem 3.0.6

### PR DESCRIPTION
**Pull request by mhchem**

### CODE REVIEW

**Comment by pkra** [comment]
Was the addition of .gitignore intentional?

**Comment by mhchem** [comment]
Well, I assumed I could not avoid it. I wanted to have a last and final test-suite check before pushing. And I assumed that having the .gitignore file was the price for that. Now I learned that I could gitignore the .gitignore file itself. Should I fix it now or leave it for one iteration and fix with the next update?

**Comment by pkra** [comment]
It's fine. I just thought I'd check. I'll merge and update the CDN tomorrow.

**Comment by pkra** [comment]
Deployed to CDN.

**Pull request merged**
