### PR TITLE
mhchem 3.0.1

### PR DESCRIPTION
**Pull request by mhchem**

### CODE REVIEW

**Comment by mhchem** [comment]
I did not squash the commits yet, so it's easier to follow what are important changes. I hope that's okay.

**Comment by mhchem** [comment]
Ooops. Error in packed version's loadComplete call. Please wait for the fixing commit.

**Comment by pkra** [comment]
@mhchem thanks for pinging me by email. Here's what I think happened. Your last comment on the PR asked to wait with a merge. I'm guessing we all saw that but didn't get any other notification since GitHub does not do alerts for commits.

I'll double check with the team on today's F2F and expect to merge the PR afterwards.

**Comment by pkra** [comment]
Sorry for not getting back to this. I'll merge and push it out to the CDN tomorrow.

**Comment by pkra** [comment]
CDN copy has been updated and seems to be refreshing endpoints. Let me know if you see any problems.

**Comment by pkra** [comment]
And thanks for the new version! :sparkler:

**Pull request merged**
