### PR TITLE
Add siunitx tex extension

### PR DESCRIPTION
**Pull request by burnpanck**
Bring latest changes to master.
I do not understand why all commits in my siunitx branch are listed in the PR, I'd thought most of it already is in master...

### CODE REVIEW

**Comment by dpvc** [comment]
> I do not understand why all commits in my siunitx branch are listed in the PR, I'd thought most of it already is in master...

It looks like your branch has never been merged into master before so all the commits are new to master.  See the [network diagram](https://github.com/mathjax/MathJax-third-party-extensions/network) for details.

**Comment by burnpanck** [comment]
Indeed apparently the previous commits were not recorded as a merge. In any case, everything up to 5987175 seems to be already in, only the last 8 commits are new (starting from the two commits mentinoning fixing of https://github.com/burnpanck/MathJax-third-party-extensions/issues/2).

**Comment by pkra** [comment]
From a quick look,

From https://github.com/mathjax/MathJax-third-party-extensions/pull/19#issuecomment-151880426

> As per F2F discussion, closing this in favor of a leaner PR.

And it seems I simply pushed https://github.com/mathjax/MathJax-third-party-extensions/commit/b295584bde6ec28bdeabc38f1d9b25e18548ecde to master.

Sorry if this caused any issues.

It's not a huge issue for me but I'd still recommend a separate repo for complex 3rd party extensions like this (e.g., arabic, physics.js, and our mathjax-a11y extensions). That way, development of the extension is easier to organize (issues, tests, build tools) and this repo stays lean. In that case, only production ready copies are pushed to this repo.

**Comment by burnpanck** [comment]
That's fine with me. I just found a relatively old issue on my repo suggesting that I should merge: https://github.com/burnpanck/MathJax-third-party-extensions/issues/3
So is there anything we should do to make it easier for people interested in trying out `siunitx` even when it is not yet officially production ready? Or should we simply redirect them to rawgit for the time being?

**Comment by pkra** [comment]
> That's fine with me. 

Ok. So I'd suggest to close this PR and create a new one with just the production ready files.

> So is there anything we should do to make it easier for people interested in trying out siunitx even when it is not yet officially production ready? Or should we simply redirect them to rawgit for the time being?

Whatever works for you. Once the fix is merged here, the CDN will be updated with the update version. For development, I would probably suggest rawgit or github pages.

**Comment by OmarIthawi** [comment]
Hi @burnpanck, I was in the same situation when I needed my Arabic extention to be CDN-hosted for testing (#20) at the same time it needed so much work before it gets merged. The easy way was to use github pages and host it:

 - https://github.com/Edraak/arabic-extension-static (the repo)
 - http://edraak.github.io/arabic-extension-static/arabic/arabic.js (the link)

> Whatever works for you. Once the fix is merged here, the CDN will be updated with the update version. For development, I would probably suggest rawgit or github pages.

There's a problem with rawgit, Google Chrome (and probably other browsers) will refuse (rightly) to interpret is as JavaScript for security reasons.

So [Github Pages](https://pages.github.com/) is the way to go, or you could use any ad-hoc CDN.

**Comment by pkra** [comment]
@burnpanck I'm closing this PR for now as discussed above.

**Comment by burnpanck** [comment]
Sure. I was really just blindly PR'ing because an issue in my repo told me so. In fact, the current state does not add much new, but mainly contains WIP. I attempted to finish that past weekend, however, still not done yet. Hopefully, I can still do so and then really PR something production ready.

**Comment by pkra** [comment]
Thanks for the update, @burnpanck. Looking forward to the next version!

**Pull request closed without merging**
